export enum View {
  GLOBAL_DASHBOARD,
  GLOBAL_PROJECT_LIST,
  PROJECT_DASHBOARD,
  PROJECT_QUERY_DEFINITION,
  PROJECT_COHORT_BROWSER,
  PROJECT_RELEVANCE_PATIENT_VIEW
}

export enum PatientView {
  SUMMARY,
  STRUCTURED_DATA,
  UNSTRUCTURED_DATA
}
